### ISSUE TITLE
Japanese Hiragana text doesn't copy over to the .txt files correctly

### ISSUE THREAD

**Issue by TheMooSpl** [GrandyB/SheetsIO#48]
**Is your feature request related to a problem? Please describe.**
Currently, SheetIO isn't pulling Japanese hiragana characters into .txt files, for example:
What's on the google sheet: αWings☆つばさ
What's in the .txt file: αWings☆�?��?��?�#2961
What's in OBS: αWings☆�?��?��?�#2961

When I copy "αWings☆つばさ" into the .txt manually, it displays correctly in OBS.

**Describe the solution you'd like**
SheetIO to pull in hiragana using UTF-8

**Describe alternatives you've considered**
The alternative is putting each name with hiragana in manually, but it is common to have both English and Japanese in a name with what I do. Each team has a max of 8 players, that's around max 16 players displayed onscreen so grabbing all that info and inputting it manually is very difficult.

**Additional context**
These are some of the names that won't display. One I due to emotes, which I'm not too concerned about but the others are all hiragana. You can see that the katakana shows up but not the hiragana.
![image](https://user-images.githubusercontent.com/124401250/216709936-82880852-89ca-481d-aec4-0371b62f0536.png)

**Comment by GrandyB** [comment]
Thank you for the detailed examples; will replicate locally and see what can be done.

**Comment by GrandyB** [comment]
Replicated and fixed.
Both the response reader (from the API call to Google) and the file writer (to text file) were both not using UTF-8. They now do.

Tried "αWings☆つばさ" and "%22~👀🤍", both of which get into the text files now, so hopefully both the Japanese characters and emojis should work.

Will push it up shortly.

**Comment by GrandyB** [comment]
@TheMooSpl can you please try out the hotfix on the latest pre-release.
This build has some new changes in I'd appreciate any testing for too.

https://github.com/GrandyB/SheetsIO/releases/tag/v0.7.3.1

**Comment by TheMooSpl** [comment]
Everything seems to be in working order, the characters show up completely fine and I think the blank file failsafes are also working too.
Thank you so much for this and being so quick!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by GrandyB** [comment]
Jolly good; thanks for reporting it to me - would never have known otherwise.

Closing as fixed in 0.7.3.1
