### ISSUE TITLE
Occasional failing to load from Imgur link

### ISSUE THREAD

**Issue by ThePeachZA** [GrandyB/SheetsIO#54]
**Describe the bug**
When trying to load an image from an Imgur image link, _sometimes_ the application throws up an error saying it is unable to read the image.

**To Reproduce**
1. Have an Imgur link in a cell on Google Sheets
2. Have the config set up to read that cell with the .png file extension
3. Load config and update

**Expected behavior**
Pulls the image from Imgur and converts it into a png in the files directory

**Logs**
> 2024-56-02 12:56:12.876 [Thread-3] DEBUG application.services.FileIO - Treating 'https://i.imgur.com/hLPGkz7.png' as a remote url
> 2024-56-02 12:56:13.465 [Thread-3] DEBUG application.services.FileIO - Read [1ms]
> 2024-56-02 12:56:13.466 [Thread-3] ERROR application.panels.BasePanel - Unable to read image from URL 'https://i.imgur.com/hLPGkz7.png' - ensure it is of a supported type
> Ensure it is of a valid type: [png, jpg, jpeg, gif, bmp]
> 2024-56-02 12:56:13.466 [Thread-3] ERROR application.panels.BasePanel - application.services.FileUpdater.updateImage(FileUpdater.java:136)
> application.services.FileUpdater.updateFile(FileUpdater.java:108)
> application.services.FileUpdater.updateFiles(FileUpdater.java:89)
> application.services.UpdateController.update(UpdateController.java:100)
> application.threads.UpdateRunnable.perform(UpdateRunnable.java:54)
> application.threads.IntervalRunnable.run(IntervalRunnable.java:47)
> java.base/java.lang.Thread.run(Thread.java:833)
> ...
> 
> If unable to fix locally, please raise an issue with today's log file (in /logs) and any details on how to reproduce at https://github.com/GrandyB/SheetsIO/issues

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.7.3.1

**Comment by GrandyB** [comment]
Hi there!

This was reported to me a day or so ago directly. It appears that Imgur is experiencing some difficulties currently, so it is advised to migrate your images elsewhere for the time being.

https://status.imgur.com/

If it returns to healthy and still has issues with the program I'll give it another look.

The person I spoke to said Google drive links worked if you replaced the start with: "https://lh3.googleusercontent.com/d/". I'm sure there's other services out there which work with SheetsIO however.

If it's still an issue after switching or once you see the Imgur status healthy, don't hesitate to message.

All the best for your broadcasts! If you have a link to them, I'd love to see how the tool is being utilised.

**Comment by ThePeachZA** [comment]
Thank you for the update! Pity to hear about the Imgur stuff, but I'll definitely give the Google Drive links a try.

I've used SheetsIO since June 2021 and never looked back! Almost all the live vods on [this channel](https://www.youtube.com/c/CompetitiveOverwatchSouthAfrica) since June 2021 have been using SheetsIO. I've never had any issues that weren't of my own creating. It's been super simple to setup and super simple to teach to co-producers. 

Thank you so much for creating an epic application, and I can't wait to see future updates to it!
